# Generated by Django 4.0.4 on 2023-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('comanda_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('historial_comandes', models.CharField(max_length=30)),
                ('estat', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
